version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: saarthi-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: saarthi
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - saarthi-network

  # Backend API
  backend:
    build:
      context: ./saarthi-backend
      dockerfile: Dockerfile
    container_name: saarthi-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/saarthi
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret}
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - saarthi-network

  # Frontend App
  frontend:
    build:
      context: ./saarthi-webapp
      dockerfile: Dockerfile
    container_name: saarthi-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_AVAILABLE_CITIES=bihar
      - NEXT_PUBLIC_AVAILABLE_LANGUAGES=hi,en
      - NEXT_PUBLIC_DEFAULT_LANGUAGE=hi
      - NEXT_PUBLIC_AIRPORT_TRANSFER_ENABLED=true
      - NEXT_PUBLIC_HOURLY_RENTAL_ENABLED=true
      - NEXT_PUBLIC_OUTSTATION_ENABLED=true
      - NEXT_PUBLIC_PRESCHEDULED_RIDES_ENABLED=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - saarthi-network

volumes:
  mongodb_data:

networks:
  saarthi-network:
    driver: bridge
